# For more information on multiple pipelines, see the documentation:
#   https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html

#- pipeline.id: main
#  path.config: "/usr/share/logstash/pipeline"

#- pipeline.id: log_generator
#  path.config: "/usr/share/logstash/config/pipelines/log_generator.yml"

- pipeline.id: log_receiver
  pipeline.batch.size: 1 # in number of events
  pipeline.batch.delay: 50 # in ms
  config.string: |
    input {
      syslog {
        port => 514
        #proxy_protocol => true
      }
      #tcp {
        #port => 514
      #}
    }
    filter {
    }
    output {
      #stdout {}
      file {
        path => "/tmp/nate-%{+YYY-MM-dd}.txt"
      }
    }

